version: "2"
services:
  tester:
    build: .
    entrypoint: 
      - npm
      - test
    depends_on:
    - mongo
    environment:
      - MONGO_URI="mongodb://mongo:27017"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
